# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: [eccodes@2.19.0 jp2k=none +fortran +build_shared_libs, eckit@1.20.2 ~mpi, hdf5 ~mpi, fdb@inspect, fdb-fortran ^fdb@inspect] 
  view: false
  concretizer:
    unify: true
  config:
    install_tree:
      root: /opt/spack
